export const countriesLatamEs = [
  'España',
  'Argentina',
  'Bolivia',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Ecuador',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'México',
  'Nicaragua',
  'Panamá',
  'Paraguay',
  'Perú',
  'Puerto Rico',
  'República Dominicana',
  'Uruguay',
  'Venezuela'
];

export const provincesEs = [
  'Álava',
  'Albacete',
  'Alicante',
  'Almería',
  'Asturias',
  'Ávila',
  'Badajoz',
  'Baleares',
  'Barcelona',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón',
  'Ceuta',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Girona',
  'Granada',
  'Guadalajara',
  'Guipúzcoa',
  'Huelva',
  'Huesca',
  'Jaén',
  'La Coruña',
  'La Rioja',
  'Las Palmas',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Melilla',
  'Murcia',
  'Navarra',
  'Ourense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Vizcaya',
  'Zamora',
  'Zaragoza'
];

export const provincesLatam = [
  // México (estados)
  'Ciudad de México',
  'Estado de México',
  'Jalisco',
  'Nuevo León',
  'Puebla',
  'Guanajuato',
  'Veracruz',
  'Yucatán',
  'Querétaro',
  'Baja California',
  'Chihuahua',
  // Argentina (provincias)
  'Buenos Aires',
  'Córdoba',
  'Santa Fe',
  'Mendoza',
  'Tucumán',
  'Entre Ríos',
  'Salta',
  'Neuquén',
  // Colombia (departamentos)
  'Bogotá D.C.',
  'Antioquia',
  'Valle del Cauca',
  'Cundinamarca',
  'Atlántico',
  'Santander',
  // Chile (regiones)
  'Metropolitana de Santiago',
  'Valparaíso',
  'Biobío',
  'Maule',
  'Araucanía',
  'Los Lagos',
  // Perú (regiones)
  'Lima',
  'Arequipa',
  'Cusco',
  'Piura',
  'La Libertad',
  'Junín'
];

export const provinceOptions = [...provincesEs, ...provincesLatam].sort();
